export enum Empfaenger {
  LEER = '--',
  SPARKASSE = 'SPARKASSE',
  N26 = 'N26',
  VOLKSBANK = 'VOLKSBANK',
  BAR = 'BAR',
  DEPOT = 'DEPOT',
  EXTERN = 'EXTERN',
  SPARKONTO = 'SPARKONTO',
  RUECKLAGEN = 'RUECKLAGEN',
}
