export enum Kategorie {
  LEER = '',
  ABO = 'ABO',
  FIXKOSTEN = 'FIXKOSTEN',
  KONSUM = 'KONSUM',
  KREDIT = 'KREDIT',
  SPAREN = 'SPAREN',
  VERSICHERUNG = 'VERSICHERUNG',
  VERTRAG = 'VERTRAG',
  KONTOSTAND = 'KONTOSTAND',
  GEHALT = 'GEHALT',
}
